/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as CmsRouteRouteImport } from './app/cms/route'
import { Route as SiteRouteRouteImport } from './app/_site/route'
import { Route as CmsIndexRouteImport } from './app/cms/index'
import { Route as SiteIndexRouteImport } from './app/_site/index'
import { Route as ImagesIdRouteImport } from './app/images/$id'
import { Route as CmsImagesRouteImport } from './app/cms/images'
import { Route as CmsImageBackfillRouteImport } from './app/cms/image-backfill'
import { Route as CmsPostsIndexRouteImport } from './app/cms/posts/index'
import { Route as CmsPostsIdRouteImport } from './app/cms/posts/$id'
import { Route as SitePostsSlugRouteImport } from './app/_site/posts/$slug'

const CmsRouteRoute = CmsRouteRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIndexRoute = CmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const ImagesIdRoute = ImagesIdRouteImport.update({
  id: '/images/$id',
  path: '/images/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsImagesRoute = CmsImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsImageBackfillRoute = CmsImageBackfillRouteImport.update({
  id: '/image-backfill',
  path: '/image-backfill',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsPostsIndexRoute = CmsPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const CmsPostsIdRoute = CmsPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => CmsRouteRoute,
} as any)
const SitePostsSlugRoute = SitePostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/cms': typeof CmsRouteRouteWithChildren
  '/cms/image-backfill': typeof CmsImageBackfillRoute
  '/cms/images': typeof CmsImagesRoute
  '/images/$id': typeof ImagesIdRoute
  '/cms/': typeof CmsIndexRoute
  '/posts/$slug': typeof SitePostsSlugRoute
  '/cms/posts/$id': typeof CmsPostsIdRoute
  '/cms/posts/': typeof CmsPostsIndexRoute
}
export interface FileRoutesByTo {
  '/cms/image-backfill': typeof CmsImageBackfillRoute
  '/cms/images': typeof CmsImagesRoute
  '/images/$id': typeof ImagesIdRoute
  '/': typeof SiteIndexRoute
  '/cms': typeof CmsIndexRoute
  '/posts/$slug': typeof SitePostsSlugRoute
  '/cms/posts/$id': typeof CmsPostsIdRoute
  '/cms/posts': typeof CmsPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteRouteWithChildren
  '/cms': typeof CmsRouteRouteWithChildren
  '/cms/image-backfill': typeof CmsImageBackfillRoute
  '/cms/images': typeof CmsImagesRoute
  '/images/$id': typeof ImagesIdRoute
  '/_site/': typeof SiteIndexRoute
  '/cms/': typeof CmsIndexRoute
  '/_site/posts/$slug': typeof SitePostsSlugRoute
  '/cms/posts/$id': typeof CmsPostsIdRoute
  '/cms/posts/': typeof CmsPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cms'
    | '/cms/image-backfill'
    | '/cms/images'
    | '/images/$id'
    | '/cms/'
    | '/posts/$slug'
    | '/cms/posts/$id'
    | '/cms/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cms/image-backfill'
    | '/cms/images'
    | '/images/$id'
    | '/'
    | '/cms'
    | '/posts/$slug'
    | '/cms/posts/$id'
    | '/cms/posts'
  id:
    | '__root__'
    | '/_site'
    | '/cms'
    | '/cms/image-backfill'
    | '/cms/images'
    | '/images/$id'
    | '/_site/'
    | '/cms/'
    | '/_site/posts/$slug'
    | '/cms/posts/$id'
    | '/cms/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  CmsRouteRoute: typeof CmsRouteRouteWithChildren
  ImagesIdRoute: typeof ImagesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/': {
      id: '/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof CmsIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/images/$id': {
      id: '/images/$id'
      path: '/images/$id'
      fullPath: '/images/$id'
      preLoaderRoute: typeof ImagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/images': {
      id: '/cms/images'
      path: '/images'
      fullPath: '/cms/images'
      preLoaderRoute: typeof CmsImagesRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/image-backfill': {
      id: '/cms/image-backfill'
      path: '/image-backfill'
      fullPath: '/cms/image-backfill'
      preLoaderRoute: typeof CmsImageBackfillRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/posts/': {
      id: '/cms/posts/'
      path: '/posts'
      fullPath: '/cms/posts/'
      preLoaderRoute: typeof CmsPostsIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/cms/posts/$id': {
      id: '/cms/posts/$id'
      path: '/posts/$id'
      fullPath: '/cms/posts/$id'
      preLoaderRoute: typeof CmsPostsIdRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/_site/posts/$slug': {
      id: '/_site/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof SitePostsSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
  }
}

interface SiteRouteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SitePostsSlugRoute: typeof SitePostsSlugRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SitePostsSlugRoute: SitePostsSlugRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

interface CmsRouteRouteChildren {
  CmsImageBackfillRoute: typeof CmsImageBackfillRoute
  CmsImagesRoute: typeof CmsImagesRoute
  CmsIndexRoute: typeof CmsIndexRoute
  CmsPostsIdRoute: typeof CmsPostsIdRoute
  CmsPostsIndexRoute: typeof CmsPostsIndexRoute
}

const CmsRouteRouteChildren: CmsRouteRouteChildren = {
  CmsImageBackfillRoute: CmsImageBackfillRoute,
  CmsImagesRoute: CmsImagesRoute,
  CmsIndexRoute: CmsIndexRoute,
  CmsPostsIdRoute: CmsPostsIdRoute,
  CmsPostsIndexRoute: CmsPostsIndexRoute,
}

const CmsRouteRouteWithChildren = CmsRouteRoute._addFileChildren(
  CmsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRouteRoute: SiteRouteRouteWithChildren,
  CmsRouteRoute: CmsRouteRouteWithChildren,
  ImagesIdRoute: ImagesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
