/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as TestRouteImport } from './app/test'
import { Route as DashboardRouteImport } from './app/dashboard'
import { Route as CmsRouteImport } from './app/cms'
import { Route as IndexRouteImport } from './app/index'
import { Route as CmsIndexRouteImport } from './app/cms/index'
import { Route as PostsSlugRouteImport } from './app/posts/$slug'
import { Route as ImagesIdRouteImport } from './app/images/$id'
import { Route as CmsImagesRouteImport } from './app/cms/images'
import { Route as CmsPostsIndexRouteImport } from './app/cms/posts/index'
import { Route as CmsPostsIdRouteImport } from './app/cms/posts/$id'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIndexRoute = CmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmsRoute,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesIdRoute = ImagesIdRouteImport.update({
  id: '/images/$id',
  path: '/images/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsImagesRoute = CmsImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => CmsRoute,
} as any)
const CmsPostsIndexRoute = CmsPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => CmsRoute,
} as any)
const CmsPostsIdRoute = CmsPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => CmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cms': typeof CmsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/test': typeof TestRoute
  '/cms/images': typeof CmsImagesRoute
  '/images/$id': typeof ImagesIdRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/cms/': typeof CmsIndexRoute
  '/cms/posts/$id': typeof CmsPostsIdRoute
  '/cms/posts/': typeof CmsPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/test': typeof TestRoute
  '/cms/images': typeof CmsImagesRoute
  '/images/$id': typeof ImagesIdRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/cms': typeof CmsIndexRoute
  '/cms/posts/$id': typeof CmsPostsIdRoute
  '/cms/posts': typeof CmsPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cms': typeof CmsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/test': typeof TestRoute
  '/cms/images': typeof CmsImagesRoute
  '/images/$id': typeof ImagesIdRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/cms/': typeof CmsIndexRoute
  '/cms/posts/$id': typeof CmsPostsIdRoute
  '/cms/posts/': typeof CmsPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cms'
    | '/dashboard'
    | '/test'
    | '/cms/images'
    | '/images/$id'
    | '/posts/$slug'
    | '/cms/'
    | '/cms/posts/$id'
    | '/cms/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/test'
    | '/cms/images'
    | '/images/$id'
    | '/posts/$slug'
    | '/cms'
    | '/cms/posts/$id'
    | '/cms/posts'
  id:
    | '__root__'
    | '/'
    | '/cms'
    | '/dashboard'
    | '/test'
    | '/cms/images'
    | '/images/$id'
    | '/posts/$slug'
    | '/cms/'
    | '/cms/posts/$id'
    | '/cms/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CmsRoute: typeof CmsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  TestRoute: typeof TestRoute
  ImagesIdRoute: typeof ImagesIdRoute
  PostsSlugRoute: typeof PostsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/': {
      id: '/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof CmsIndexRouteImport
      parentRoute: typeof CmsRoute
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$id': {
      id: '/images/$id'
      path: '/images/$id'
      fullPath: '/images/$id'
      preLoaderRoute: typeof ImagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/images': {
      id: '/cms/images'
      path: '/images'
      fullPath: '/cms/images'
      preLoaderRoute: typeof CmsImagesRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/posts/': {
      id: '/cms/posts/'
      path: '/posts'
      fullPath: '/cms/posts/'
      preLoaderRoute: typeof CmsPostsIndexRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/posts/$id': {
      id: '/cms/posts/$id'
      path: '/posts/$id'
      fullPath: '/cms/posts/$id'
      preLoaderRoute: typeof CmsPostsIdRouteImport
      parentRoute: typeof CmsRoute
    }
  }
}

interface CmsRouteChildren {
  CmsImagesRoute: typeof CmsImagesRoute
  CmsIndexRoute: typeof CmsIndexRoute
  CmsPostsIdRoute: typeof CmsPostsIdRoute
  CmsPostsIndexRoute: typeof CmsPostsIndexRoute
}

const CmsRouteChildren: CmsRouteChildren = {
  CmsImagesRoute: CmsImagesRoute,
  CmsIndexRoute: CmsIndexRoute,
  CmsPostsIdRoute: CmsPostsIdRoute,
  CmsPostsIndexRoute: CmsPostsIndexRoute,
}

const CmsRouteWithChildren = CmsRoute._addFileChildren(CmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CmsRoute: CmsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  TestRoute: TestRoute,
  ImagesIdRoute: ImagesIdRoute,
  PostsSlugRoute: PostsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
